In [6]:
import pandas as pd
import numpy as np

In [7]:
df_raw = pd.read_csv("ISIC_2020_Training_GroundTruth.csv")
df_raw

,image_name,patient_id,sex,age_approx,anatom_site_general_challenge,diagnosis,benign_malignant,target,melanoma,seborrheic_keratosis
0,ISIC_2637011,IP_7279968,male,45.0,head/neck,unknown,benign,0,0,0
1,ISIC_0015719,IP_3075186,female,45.0,upper extremity,unknown,benign,0,0,0
2,ISIC_0052212,IP_2842074,female,50.0,lower extremity,nevus,benign,0,0,0
3,ISIC_0068279,IP_6890425,female,45.0,head/neck,unknown,benign,0,0,0
4,ISIC_0074268,IP_8723313,female,55.0,upper extremity,unknown,benign,0,0,0
...,...,...,...,...,...,...,...,...,...,...
33121,ISIC_9999134,IP_6526534,male,50.0,torso,unknown,benign,0,0,0
33122,ISIC_9999320,IP_3650745,male,65.0,torso,unknown,benign,0,0,0
33123,ISIC_9999515,IP_2026598,male,20.0,lower extremity,unknown,benign,0,0,0
33124,ISIC_9999666,IP_7702038,male,50.0,lower extremity,unknown,benign,0,0,0
33125,ISIC_9999806,IP_0046310,male,45.0,torso,nevus,benign,0,0,0

In [8]:
df_labels = df_raw[["image_name", "target"]]
df_labels = df_labels.rename(columns={"image_name":"image_id", "target":"cancer"})

In [9]:
## Randomize the order (to deal with clinic bias and maybe more)
df_random = df_labels.sample(frac=1)
df_random

           image_id  cancer
30409  ISIC_9186921       0
27294  ISIC_8266094       0
4230   ISIC_1373747       0
8104   ISIC_2523171       0
23383  ISIC_7107771       0
...             ...     ...
11678  ISIC_3596877       0
29436  ISIC_8898680       0
20139  ISIC_6122044       0
7487   ISIC_2339423       0
3041   ISIC_1013796       0

[33126 rows x 2 columns]

In [10]:
## Save this to csv (maybe not needed)
df_random.to_csv("ISIC_2020_GroundTruth_Random.csv")

In [11]:
## Pick X random images where cancer = 1, and X where cancer = 0
## First part with .loc is a "where-statement", and sample(100) takes 100 items at random from the random list
size_X = 500
df_sample_cancer = df_random.loc[(df_random["cancer"] == 1)].sample(size_X)
print(df_sample_cancer)

## Same as above, but with no_cancer
df_sample_no_cancer = df_random.loc[(df_random["cancer"] == 0)].sample(size_X)
print(df_sample_no_cancer)

           image_id  cancer
20904  ISIC_6348638       1
774    ISIC_0337631       1
28175  ISIC_8527092       1
33050  ISIC_9978107       1
28028  ISIC_8483382       1
...             ...     ...
22520  ISIC_6829008       1
475    ISIC_0250839       1
3651   ISIC_1200192       1
26954  ISIC_8167374       1
23854  ISIC_7242384       1

[500 rows x 2 columns]
           image_id  cancer
32584  ISIC_9837063       0
21230  ISIC_6442768       0
11783  ISIC_3628451       0
16616  ISIC_5084654       0
11091  ISIC_3419245       0
...             ...     ...
18533  ISIC_5630228       0
4451   ISIC_1441260       0
21714  ISIC_6577841       0
3283   ISIC_1091280       0
5635   ISIC_1787026       0

[500 rows x 2 columns]

In [12]:
## Concat the two sample groups:
df_sample = pd.concat([df_sample_cancer,df_sample_no_cancer])
df_sample

           image_id  cancer
20904  ISIC_6348638       1
774    ISIC_0337631       1
28175  ISIC_8527092       1
33050  ISIC_9978107       1
28028  ISIC_8483382       1
...             ...     ...
18533  ISIC_5630228       0
4451   ISIC_1441260       0
21714  ISIC_6577841       0
3283   ISIC_1091280       0
5635   ISIC_1787026       0

[1000 rows x 2 columns]

In [13]:
## Check that there are exactly 200 image_ids (no duplicates) and only 2 classes (cancer / no-cancer)
df_sample.nunique()

image_id    1000
cancer         2
dtype: int64

In [14]:
## Save the sample data in a csv file
df_sample.to_csv("ISIC_2020_unlabeled_images.csv")